name: Dev Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'terraform/storage/environments/dev.tfvars'
      - '.github/workflows/dev.yaml'

jobs:
  dev-deploy:
    name: "Trigger Terraform Workflow"
    uses: './.github/workflows/deploy.yaml'
    with:
      environment: dev
