name: Test Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'terraform/storage/environments/test.tfvars'
      - '.github/workflows/test.yaml'

jobs:
  dev-deploy:
    name: "Trigger Terraform Workflow"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: '.github/workflows/deploy.yaml@main'
        with:
          environment: test
